//
//  Generate.swift
//  tinyGLL
//
//  Emits a standalone CNP parser for the grammar currently in memory.
//

import Foundation

// The generated file is the *compiled* counterpart of parseInput(): where the interpreter
// walks the GrammarNode graph and switches on cL.kind, the generated parser switches on an
// integer slot id and has one case per grammar slot, with every grammar fact folded into a
// literal. That is the BSR paper's §5.3.2 template structure — a code label per slot — with
// 'goto L' written as 'cL = <id>' and 'goto L0' as 'continue nextDescriptor', Swift having
// no goto.
//
// Lookahead is left out, exactly as in the interpreter: addDescriptorsForAlternates adds a
// descriptor for every alternate and the terminal match is inline, so no FIRST/FOLLOW sets
// and no testSelect() are needed. In CNP lookahead only suppresses descriptors — it is not
// load bearing for correctness or termination, which come from 'unique'. Both parsers
// therefore build the *same* BSR, which is what makes them diffable against each other.
//
// Slot ids are GrammarNode.number, so the two BSRs are keyed identically too, right down to
// the engine's deliberate relabelling: a yield is keyed by the dot-BEFORE node, and a
// completed alternate is keyed by its LHS nonterminal (see Engine.swift 'call').

nonisolated enum GenerateError: Error, CustomStringConvertible {
    case missingStartSymbol

    var description: String { "cannot generate: missing start symbol 'S'" }
}

/// Writes a standalone parser for `parser`'s grammar to 'GeneratedParser.swift' and returns
/// the path written. Defaults to a 'tinyGLL-generated' folder beside the sources;
/// `directory` overrides that, which the benchmark uses to keep its throwaway copy from
/// overwriting the parser generated for the grammar you were actually working on.
@discardableResult
nonisolated func generate(from parser: Parser, to directory: URL? = nil) throws -> URL {
    guard let start = parser.nonTerminalDefinitions["S"] else {
        throw GenerateError.missingStartSymbol
    }

    // Deterministic order: node numbers follow the grammar text, dictionaries do not.
    let definitions = parser.nonTerminalDefinitions.values.sorted { $0.number < $1.number }

    var out = ""
    func line(_ text: String = "", indent: Int = 0) {
        out += String(repeating: "    ", count: indent) + text + "\n"
    }

    // MARK: tables

    // altsOf: LHS nonterminal -> the entry slot of each alternate. The entry is alt.seq!,
    // not the ALT node itself, matching addDescriptorsForAlternates.
    var altsOf: [(Int, [Int])] = []
    // seqOf: RHS nonterminal slot -> its successor. rtn() stores the dot-BEFORE node on the
    // return edge and needs the dot-AFTER slot to restart from; this recovers it.
    var seqOf: [(Int, Int)] = []

    for lhs in definitions {
        var entries: [Int] = []
        var alt = lhs.alt
        while let a = alt {
            entries.append(a.seq!.number)
            alt = a.alt
        }
        altsOf.append((lhs.number, entries))
    }

    for lhs in definitions {
        var alt = lhs.alt
        while let a = alt {
            var node = a.seq
            while let n = node, n.kind != .END {
                if n.kind == .N { seqOf.append((n.number, n.seq!.number)) }
                node = n.seq
            }
            alt = a.alt
        }
    }

    // MARK: preamble

    line("//")
    line("//  GeneratedParser.swift")
    line("//")
    line("//  Generated by tinyGLL — do not edit.")
    line("//")
    line("//  Grammar: \(String(parser.syntax).trimmingCharacters(in: .whitespacesAndNewlines))")
    line("//")
    line("//  A standalone CNP parser: the grammar is encoded in the switch below, one case")
    line("//  per grammar slot, so there is no grammar graph and no grammar reader here.")
    line("//")
    line()
    line("import Foundation")
    line()
    // 'var', not 'let': --time below reassigns it to sweep a family of inputs.
    line("var input: [Character] = Array(\"\(swiftLiteral(String(parser.input)))\")")
    line()

    // MARK: engine

    line("// MARK: - Engine (grammar independent)")
    line()
    line("""
    struct Descriptor: Hashable {
        let L: Int                  // grammar slot
        let k: Int                  // cluster index
        let i: Int                  // input index
    }

    var unique: Set<Descriptor> = []
    var remaining: [Descriptor] = []

    var cL = 0
    var cU = 0
    var cI = 0

    func addDescriptor(L: Int, k: Int, i: Int) {
        let d = Descriptor(L: L, k: k, i: i)
        if unique.insert(d).inserted {
            remaining.append(d)
        }
    }

    func addDescriptorsForAlternates(X: Int, j: Int) {
        for entry in altsOf[X, default: []] {
            addDescriptor(L: entry, k: j, i: j)
        }
    }

    func getDescriptor() -> Bool {
        if remaining.isEmpty {
            return false
        } else {
            let d = remaining.removeLast()
            cL = d.L
            cU = d.k
            cI = d.i
            return true
        }
    }

    struct BinarySpan: Hashable, Comparable, CustomStringConvertible {
        let i: Int
        let k: Int
        let j: Int
        var description: String { "\\(i):\\(k):\\(j)" }

        static func < (lhs: BinarySpan, rhs: BinarySpan) -> Bool {
            if lhs.i != rhs.i { return lhs.i < rhs.i }
            if lhs.k != rhs.k { return lhs.k < rhs.k }
            return lhs.j < rhs.j
        }
    }

    // Sized by parse(), not here: the generated file is compiled as a main file, so global
    // initialisers run in source order and this one would read slotCount too early.
    var yields: [Set<BinarySpan>] = []

    func addYield(L: Int, i: Int, k: Int, j: Int) {
        yields[L].insert(BinarySpan(i: i, k: k, j: j))
    }

    struct ParsePosition: Hashable {
        let slot: Int
        let index: Int
    }

    final class ParseCluster {
        var returns: Set<ParsePosition> = []
        var pops: Set<Int> = []
    }

    var crf: [ParsePosition: ParseCluster] = [:]

    /// Paper: call(L, i, j). 'slot' is the dot-BEFORE node used as the yield key, 'next' the
    /// dot-AFTER slot to resume at, 'X' the nonterminal being entered.
    func call(slot: Int, X: Int, next: Int) {
        let returnEdge = ParsePosition(slot: slot, index: cU)
        let clusterKey = ParsePosition(slot: X, index: cI)

        if let existingCluster = crf[clusterKey] {
            if existingCluster.returns.insert(returnEdge).inserted {
                for pop in existingCluster.pops {
                    addDescriptor(L: next, k: cU, i: pop)
                    addYield(L: slot, i: cU, k: cI, j: pop)
                }
            }
        } else {
            let newCluster = ParseCluster()
            crf[clusterKey] = newCluster
            newCluster.returns.insert(returnEdge)
            addDescriptorsForAlternates(X: X, j: cI)
        }
    }

    /// Paper: rtn(X, k, j) — k and j are read from the registers cU and cI.
    func rtn(X: Int) {
        let clusterKey = ParsePosition(slot: X, index: cU)
        guard let cluster = crf[clusterKey] else { return }

        if cluster.pops.insert(cI).inserted {
            for returnEdge in cluster.returns {
                addDescriptor(L: seqOf[returnEdge.slot]!, k: returnEdge.index, i: cI)
                addYield(L: returnEdge.slot, i: returnEdge.index, k: cU, j: cI)
            }
        }
    }
    """)
    line()

    // MARK: grammar tables

    line("// MARK: - Grammar tables")
    line()
    line("let slotCount = \(parser.nodeCount)")
    line("let startSymbol = \(start.number)")
    line("let altsOf: [Int: [Int]] = [\(altsOf.map { "\($0.0): [\($0.1.map(String.init).joined(separator: ", "))]" }.joined(separator: ", "))]")
    line("let seqOf: [Int: Int] = [\(seqOf.isEmpty ? ":" : seqOf.map { "\($0.0): \($0.1)" }.joined(separator: ", "))]")
    line()

    // MARK: the unrolled descriptor loop

    line("// MARK: - Grammar (one case per slot)")
    line()
    line("func parse() {")
    line("yields = Array(repeating: [], count: slotCount)", indent: 1)
    line("crf[ParsePosition(slot: startSymbol, index: 0)] = ParseCluster()", indent: 1)
    line("addDescriptorsForAlternates(X: startSymbol, j: 0)", indent: 1)
    line()
    line("nextDescriptor: while getDescriptor() {", indent: 1)
    line("while true {", indent: 2)
    line("switch cL {", indent: 3)

    for lhs in definitions {
        var alt = lhs.alt
        while let a = alt {
            var node = a.seq
            while let n = node {
                let slot = dottedSlot(alternate: a, lhs: lhs, dot: n)
                switch n.kind {
                case .T:
                    line("case \(n.number):  // \(slot)", indent: 3)
                    line("if cI < input.count && input[cI] == \"\(swiftLiteral(String(n.name)))\" {", indent: 4)
                    line("addYield(L: \(n.number), i: cU, k: cI, j: cI + 1)", indent: 5)
                    line("cI += 1", indent: 5)
                    line("cL = \(n.seq!.number)", indent: 5)
                    line("} else {", indent: 4)
                    line("continue nextDescriptor", indent: 5)
                    line("}", indent: 4)
                case .EPS:
                    line("case \(n.number):  // \(slot)", indent: 3)
                    line("addYield(L: \(n.number), i: cU, k: cI, j: cI)", indent: 4)
                    line("cL = \(n.seq!.number)", indent: 4)
                case .N:
                    line("case \(n.number):  // \(slot)", indent: 3)
                    line("call(slot: \(n.number), X: \(n.alt!.number), next: \(n.seq!.number))", indent: 4)
                    line("continue nextDescriptor", indent: 4)
                case .END:
                    line("case \(n.number):  // \(slot)", indent: 3)
                    line("addYield(L: \(lhs.number), i: cU, k: cU, j: cI)", indent: 4)
                    line("rtn(X: \(lhs.number))", indent: 4)
                    line("continue nextDescriptor", indent: 4)
                case .ALT:
                    break   // ALT is never a descriptor target: ntAdd enters at alt.seq
                }
                if n.kind == .END { break }
                node = n.seq
            }
            alt = a.alt
        }
    }

    line("default:", indent: 3)
    line("fatalError(\"no code for slot \\(cL)\")", indent: 4)
    line("}", indent: 3)
    line("}", indent: 2)
    line("}", indent: 1)
    line("}")
    line()

    // MARK: reporting

    // Top-level code rather than an @main type: compiling one file on its own makes it the
    // main file, so plain 'swiftc GeneratedParser.swift' works with no extra flags. (@main
    // would need -parse-as-library, since a lone file is always in main-file position.)
    line("""
    /// True when the start symbol yields a span covering the whole input.
    var parseAccepted: Bool {
        yields[startSymbol].contains { $0.i == 0 && $0.j == input.count }
    }

    /// Clears everything parse() accumulates, so one process can parse several inputs.
    func reset() {
        unique = []
        remaining = []
        crf = [:]
        yields = []
        cL = 0
        cU = 0
        cI = 0
    }

    // Two ways to run:
    //   <binary>                          parse the input baked in above, print the BSR
    //   <binary> --time "bb" "bbb" …      parse each operand, printing seconds for parse()
    //
    // --time times many inputs inside ONE process on purpose: a parse here takes tens of
    // microseconds, which process startup would swamp several times over. It is what lets
    // the interpreter's benchmark compare itself against this parser input for input.
    let operands = CommandLine.arguments.dropFirst().filter { !$0.hasPrefix("--") }

    if CommandLine.arguments.contains("--time") {
        // Discarded warm-up on the baked-in input, matching the interpreter's: the first
        // parse in a process pays one-off allocation costs that would otherwise land
        // entirely on the first — and so most sensitive — operand.
        let warmUp = input
        for _ in 0..<3 {
            input = warmUp
            reset()
            parse()
        }

        for operand in operands {
            input = Array(operand)
            reset()

            let start = DispatchTime.now().uptimeNanoseconds
            parse()
            let elapsed = DispatchTime.now().uptimeNanoseconds - start

            print(String(format: "%.6f", Double(elapsed) / 1_000_000_000))

            if !parseAccepted {
                FileHandle.standardError.write(Data("rejected \\"\\(operand)\\"\\n".utf8))
            }
        }
    } else {
        if let operand = operands.first { input = Array(operand) }
        parse()

        print(parseAccepted ? "Parse pass" : "Parse fail")
        for (slot, spans) in yields.enumerated() where !spans.isEmpty {
            print("slot \\(slot): \\(spans.sorted().map(\\.description).joined(separator: " "))")
        }
    }
    """)

    // Written BESIDE tinyGLL/, never inside it. 'tinyGLL' is a
    // PBXFileSystemSynchronizedRootGroup, so any .swift file inside it is added to the
    // tinyGLL target automatically — and this one redeclares Descriptor, BinarySpan,
    // ParsePosition, input, yields and friends, all of which Engine.swift already owns, on
    // top of being top-level code that would re-break @main. Dropping it next to the engine
    // breaks the build the moment Xcode notices the file. Outside the synchronized folder it
    // stays invisible to the project, which is what "standalone" wants anyway.
    let outputDirectory = directory ?? URL(filePath: #filePath)
        .deletingLastPathComponent()      // tinyGLL/
        .deletingLastPathComponent()      // repository root
        .appending(path: "tinyGLL-generated")
    try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)

    let parserFile = outputDirectory.appending(path: "GeneratedParser.swift")
    try out.write(to: parserFile, atomically: true, encoding: .utf8)
    return parserFile
}

// MARK: - Running the generated parser

/// Generates the parser for `parser`'s grammar, compiles it with swiftc -O and runs it over
/// `inputs`, returning one parse time in seconds per input — the compiled half of the
/// benchmark comparison.
///
/// Returns nil when the toolchain is unavailable or the generated source will not build, so
/// the benchmark still reports its interpreted numbers rather than failing outright.
/// Everything is done in a throwaway directory, and all `inputs` go to a single process so
/// that timings measure parse() and not process startup.
///
/// Launching swiftc needs App Sandbox off, which is why the tinyGLL target has
/// ENABLE_APP_SANDBOX = NO.
nonisolated func compiledTimings(from parser: Parser, for inputs: [String]) throws -> [Double]? {
    let work = URL(filePath: NSTemporaryDirectory())
        .appending(path: "tinyGLL-bench-\(ProcessInfo.processInfo.globallyUniqueString)")
    try FileManager.default.createDirectory(at: work, withIntermediateDirectories: true)
    defer { try? FileManager.default.removeItem(at: work) }

    let source = try generate(from: parser, to: work)
    let binary = work.appending(path: "generated")

    // xcrun rather than a bare path: on a machine with several toolchains it picks the one
    // the rest of the build uses.
    guard runTool("/usr/bin/xcrun", ["swiftc", "-O", "-o", binary.path, source.path]) != nil,
          let output = runTool(binary.path, ["--time"] + inputs)
    else {
        return nil
    }

    let timings = output.split(separator: "\n").compactMap { Double($0) }
    return timings.count == inputs.count ? timings : nil
}

/// Runs a tool to completion and returns its standard output, or nil if it could not be
/// launched or exited nonzero. Standard error is discarded: for swiftc that would be
/// diagnostics, and the nil return already says the step failed.
private nonisolated func runTool(_ launchPath: String, _ arguments: [String]) -> String? {
    let process = Process()
    process.executableURL = URL(filePath: launchPath)
    process.arguments = arguments

    // A clean DYLD environment. Anything injected into this process is otherwise inherited
    // by swiftc and by the generated binary — Xcode's preview dylib makes the binary fail to
    // launch outright, and a profiler's interposer would quietly skew the very timings the
    // benchmark exists to measure.
    var environment = ProcessInfo.processInfo.environment
    for key in environment.keys where key.hasPrefix("DYLD_") {
        environment.removeValue(forKey: key)
    }
    process.environment = environment

    let pipe = Pipe()
    process.standardOutput = pipe
    process.standardError = FileHandle.nullDevice

    do {
        try process.run()
    } catch {
        return nil
    }

    // Drain before waiting: waiting first would deadlock if the output filled the pipe.
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    process.waitUntilExit()

    guard process.terminationStatus == 0 else { return nil }
    return String(decoding: data, as: UTF8.self)
}

/// Escapes a string for embedding in a generated Swift literal. Grammar symbols are letters
/// and the input is usually letters too, but the input is typed by hand, so it cannot be
/// assumed safe.
private nonisolated func swiftLiteral(_ text: String) -> String {
    text
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
}

/// Renders an alternate with a middle dot before `dot`, e.g. "S = a·S", for the case comment.
private nonisolated func dottedSlot(alternate: GrammarNode, lhs: GrammarNode, dot: GrammarNode) -> String {
    var text = "\(lhs.name) = "
    var node = alternate.seq
    while let n = node {
        if n == dot { text += "·" }
        if n.kind == .END { break }
        text.append(n.name)
        node = n.seq
    }
    return text
}
