//
//  GeneratedParser.swift
//
//  Generated by tinyGLL — do not edit.
//
//  Grammar: S = a S | ε .
//
//  A standalone CNP parser: the grammar is encoded in the switch below, one case
//  per grammar slot, so there is no grammar graph and no grammar reader here.
//

import Foundation

var input: [Character] = Array("aa")

// MARK: - Engine (grammar independent)

struct Descriptor: Hashable {
    let L: Int                  // grammar slot
    let k: Int                  // cluster index
    let i: Int                  // input index
}

var unique: Set<Descriptor> = []
var remaining: [Descriptor] = []

var cL = 0
var cU = 0
var cI = 0

func addDescriptor(L: Int, k: Int, i: Int) {
    let d = Descriptor(L: L, k: k, i: i)
    if unique.insert(d).inserted {
        remaining.append(d)
    }
}

func addDescriptorsForAlternates(X: Int, j: Int) {
    for entry in altsOf[X, default: []] {
        addDescriptor(L: entry, k: j, i: j)
    }
}

func getDescriptor() -> Bool {
    if remaining.isEmpty {
        return false
    } else {
        let d = remaining.removeLast()
        cL = d.L
        cU = d.k
        cI = d.i
        return true
    }
}

struct BinarySpan: Hashable, Comparable, CustomStringConvertible {
    let i: Int
    let k: Int
    let j: Int
    var description: String { "\(i):\(k):\(j)" }

    static func < (lhs: BinarySpan, rhs: BinarySpan) -> Bool {
        if lhs.i != rhs.i { return lhs.i < rhs.i }
        if lhs.k != rhs.k { return lhs.k < rhs.k }
        return lhs.j < rhs.j
    }
}

// Sized by parse(), not here: the generated file is compiled as a main file, so global
// initialisers run in source order and this one would read slotCount too early.
var yields: [Set<BinarySpan>] = []

func addYield(L: Int, i: Int, k: Int, j: Int) {
    yields[L].insert(BinarySpan(i: i, k: k, j: j))
}

struct ParsePosition: Hashable {
    let slot: Int
    let index: Int
}

final class ParseCluster {
    var returns: Set<ParsePosition> = []
    var pops: Set<Int> = []
}

var crf: [ParsePosition: ParseCluster] = [:]

/// Paper: call(L, i, j). 'slot' is the dot-BEFORE node used as the yield key, 'next' the
/// dot-AFTER slot to resume at, 'X' the nonterminal being entered.
func call(slot: Int, X: Int, next: Int) {
    let returnEdge = ParsePosition(slot: slot, index: cU)
    let clusterKey = ParsePosition(slot: X, index: cI)

    if let existingCluster = crf[clusterKey] {
        if existingCluster.returns.insert(returnEdge).inserted {
            for pop in existingCluster.pops {
                addDescriptor(L: next, k: cU, i: pop)
                addYield(L: slot, i: cU, k: cI, j: pop)
            }
        }
    } else {
        let newCluster = ParseCluster()
        crf[clusterKey] = newCluster
        newCluster.returns.insert(returnEdge)
        addDescriptorsForAlternates(X: X, j: cI)
    }
}

/// Paper: rtn(X, k, j) — k and j are read from the registers cU and cI.
func rtn(X: Int) {
    let clusterKey = ParsePosition(slot: X, index: cU)
    guard let cluster = crf[clusterKey] else { return }

    if cluster.pops.insert(cI).inserted {
        for returnEdge in cluster.returns {
            addDescriptor(L: seqOf[returnEdge.slot]!, k: returnEdge.index, i: cI)
            addYield(L: returnEdge.slot, i: returnEdge.index, k: cU, j: cI)
        }
    }
}

// MARK: - Grammar tables

let slotCount = 8
let startSymbol = 0
let altsOf: [Int: [Int]] = [0: [2, 6]]
let seqOf: [Int: Int] = [3: 4]

// MARK: - Grammar (one case per slot)

func parse() {
    yields = Array(repeating: [], count: slotCount)
    crf[ParsePosition(slot: startSymbol, index: 0)] = ParseCluster()
    addDescriptorsForAlternates(X: startSymbol, j: 0)

    nextDescriptor: while getDescriptor() {
        while true {
            switch cL {
            case 2:  // S = ·aS
                if cI < input.count && input[cI] == "a" {
                    addYield(L: 2, i: cU, k: cI, j: cI + 1)
                    cI += 1
                    cL = 3
                } else {
                    continue nextDescriptor
                }
            case 3:  // S = a·S
                call(slot: 3, X: 0, next: 4)
                continue nextDescriptor
            case 4:  // S = aS·
                addYield(L: 0, i: cU, k: cU, j: cI)
                rtn(X: 0)
                continue nextDescriptor
            case 6:  // S = ·ε
                addYield(L: 6, i: cU, k: cI, j: cI)
                cL = 7
            case 7:  // S = ε·
                addYield(L: 0, i: cU, k: cU, j: cI)
                rtn(X: 0)
                continue nextDescriptor
            default:
                fatalError("no code for slot \(cL)")
            }
        }
    }
}

/// True when the start symbol yields a span covering the whole input.
var parseAccepted: Bool {
    yields[startSymbol].contains { $0.i == 0 && $0.j == input.count }
}

/// Clears everything parse() accumulates, so one process can parse several inputs.
func reset() {
    unique = []
    remaining = []
    crf = [:]
    yields = []
    cL = 0
    cU = 0
    cI = 0
}

// Two ways to run:
//   <binary>                          parse the input baked in above, print the BSR
//   <binary> --time "bb" "bbb" …      parse each operand, printing seconds for parse()
//
// --time times many inputs inside ONE process on purpose: a parse here takes tens of
// microseconds, which process startup would swamp several times over. It is what lets
// the interpreter's benchmark compare itself against this parser input for input.
let operands = CommandLine.arguments.dropFirst().filter { !$0.hasPrefix("--") }

if CommandLine.arguments.contains("--time") {
    // Discarded warm-up on the baked-in input, matching the interpreter's: the first
    // parse in a process pays one-off allocation costs that would otherwise land
    // entirely on the first — and so most sensitive — operand.
    let warmUp = input
    for _ in 0..<3 {
        input = warmUp
        reset()
        parse()
    }

    for operand in operands {
        input = Array(operand)
        reset()

        let start = DispatchTime.now().uptimeNanoseconds
        parse()
        let elapsed = DispatchTime.now().uptimeNanoseconds - start

        print(String(format: "%.6f", Double(elapsed) / 1_000_000_000))

        if !parseAccepted {
            FileHandle.standardError.write(Data("rejected \"\(operand)\"\n".utf8))
        }
    }
} else {
    if let operand = operands.first { input = Array(operand) }
    parse()

    print(parseAccepted ? "Parse pass" : "Parse fail")
    for (slot, spans) in yields.enumerated() where !spans.isEmpty {
        print("slot \(slot): \(spans.sorted().map(\.description).joined(separator: " "))")
    }
}
