import Foundation
import Testing

/// Writes the swift-syntax test snippets as a fuzzer seed corpus (`### label` blocks, the format of
/// `SwiftSyntaxFuzzer/seeds/known-problems.txt`). Opt-in: set `APUS_EXPORT_FUZZ_SEEDS=<path>` in the
/// test plan (or `TEST_RUNNER_APUS_EXPORT_FUZZ_SEEDS` via xcodebuild) and run this suite. Going through
/// the test target means the compiler has already decoded every raw / multi-line string literal.
///
/// Only swift-syntax 603 and project fixtures: many 604 snippets need experimental parser features
/// that the fuzz probe does not enable, so they would surface as noise.
@Suite("Fuzzer seed export", .enabled(if: ProcessInfo.processInfo.environment["APUS_EXPORT_FUZZ_SEEDS"] != nil,
                                      "opt-in: set APUS_EXPORT_FUZZ_SEEDS=<output path>"))
struct FuzzSeedExport {
    @Test func exportSeeds() throws {
        let path = try #require(ProcessInfo.processInfo.environment["APUS_EXPORT_FUZZ_SEEDS"])
        let collections: [(String, [SwiftSnippet])] = [
            ("translated", translatedSnippets), ("attribute", attributeSnippets),
            ("declaration", declarationSnippets), ("expression", expressionSnippets),
            ("statement", statementSnippets), ("type", typeSnippets), ("pattern", patternSnippets),
            ("reject", allRejectSnippets),
            ("phase1", phase1Snippets), ("phase2-literal", phase2LiteralSnippets),
            ("phase2-infix", phase2InfixSnippets), ("phase2-postfix", phase2PostfixSnippets),
            ("phase3-function", phase3FunctionSnippets), ("phase3-branch", phase3BranchSnippets),
            ("phase3-modifier", phase3ModifierSnippets), ("phase3-enum-case", phase3EnumCaseSnippets),
            ("phase3-statement", phase3StatementSnippets), ("phase3-type", phase3TypeSnippets),
            ("phase4-attr", phase4AttrSnippets), ("phase4-closure", phase4ClosureSnippets),
            ("phase4-decl", phase4DeclSnippets), ("phase4-type", phase4TypeSnippets),
            ("phase4-coroutine", phase4CoroutineSnippets), ("phase4-pattern", phase4PatternSnippets),
            ("phase4-precedence", phase4PrecedenceSnippets), ("phase4-ifconfig", phase4IfConfigSnippets),
            ("phase4-string", phase4StringSnippets), ("phase4-keypath", phase4KeyPathSnippets),
            ("phase4-import", phase4ImportSnippets), ("phase4-macro", phase4MacroSnippets),
            ("phase4-loop", phase4LoopSnippets), ("phase4-accessor", phase4AccessorSnippets),
            ("phase4-misc", phase4MiscSnippets), ("phase4-available", phase4AvailableSnippets),
            ("fuzz-harvest", fuzzHarvestSnippets),
        ]
        var seen = Set<String>()
        var out = "# Generated by ApusApusTests/FuzzSeedExport.swift — do not edit; re-export instead.\n\n"
        for (collection, snippets) in collections {
            for snippet in snippets {
                let source = snippet.source.trimmingCharacters(in: .whitespacesAndNewlines)
                // A `###` line inside a source would start a new block when the file is read back.
                guard !source.isEmpty, !source.contains("\n### "), seen.insert(source).inserted else { continue }
                out += "### \(collection):\(snippet.label)\n\(source)\n\n"
            }
        }
        try out.write(toFile: path, atomically: true, encoding: .utf8)
        print("wrote \(seen.count) seeds to \(path)")
    }
}
