#!/usr/bin/env python3
"""Harvest the NEGATIVE corpus: swift-syntax `assertParse(..., diagnostics: [...])`
calls (the error/recovery tests the accept-extractor deliberately skips).

Markers (1️⃣, ℹ️, …) are stripped, leaving the malformed source. Emits
`AdventTests/SwiftSyntaxRejects.swift` with per-domain `*RejectSnippets` arrays and a
`@Suite("SwiftSyntax - Rejects")` carrying two categories:

  • "SwiftSyntax rejects" — baseline: `Parser.parse(source).hasError == true`.
  • "Advent rejects"      — `adventParse == nil`, wrapped in `withKnownIssue` (xfail),
                            so a case that STARTS rejecting correctly is surfaced.

Run from the repo root:  python3 tools/extract_rejects.py
"""
import os, sys, glob

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_snippets import (
    find_matching_paren, extract_first_string_arg, has_diagnostics,
    has_marker_chars, strip_markers, has_underscored_attrs, find_test_func,
)

TESTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "swiftsyntax_tests")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "AdventTests", "SwiftSyntaxRejects.swift")
VERSION = "603.0.1"


def collect_rejects(filepath):
    """Mirror extract_snippets.process_file but keep ONLY has_diag calls."""
    with open(filepath, encoding="utf-8") as f:
        source = f.read()
    basename = os.path.splitext(os.path.basename(filepath))[0]
    out, counters, pos = [], {}, 0
    while True:
        idx = source.find("assertParse(", pos)
        if idx == -1:
            break
        paren_start = idx + len("assertParse")
        paren_end = find_matching_paren(source, paren_start)
        if paren_end == -1:
            pos = idx + 1
            continue
        call_body = source[paren_start + 1:paren_end]
        func_name = find_test_func(source, idx)
        result = extract_first_string_arg(call_body)
        if result is None:            # interpolated / non-literal — skip
            pos = paren_end + 1
            continue
        literal, rest = result
        if has_diagnostics(rest):     # <-- the NEGATIVE corpus (inverse of accept path)
            counters[func_name] = counters.get(func_name, 0) + 1
            lit = strip_markers(literal) if has_marker_chars(literal) else literal
            out.append({
                "label": f"{func_name}#{counters[func_name]}",
                "literal": lit,
                "origin": f"{basename}.{func_name}",
                "underscored": has_underscored_attrs(literal),
            })
        pos = paren_end + 1
    return out


def raw_wrap(lit):
    """Re-emit a verbatim Swift string literal so it performs NO interpolation:
    bump its raw-string pound count until `\\(…)` is inert (e.g. `"a.\\(x)"` →
    `#"a.\\(x)"#`). Preserves the snippet instead of dropping it — the source
    references test-local vars we can't resolve, so we keep it as literal text."""
    n = 0
    while n < len(lit) and lit[n] == "#":
        n += 1
    p = n
    while ("\\" + "#" * p + "(") in lit:   # interpolation marker for p pounds
        p += 1
    if p == n:
        return lit
    body = lit if n == 0 else lit[n:-n]     # inner literal incl. its quotes
    return "#" * p + body + "#" * p


def fmt_array(snippets, name):
    lines = [f"let {name}: [SwiftSnippet] = ["]
    for s in snippets:
        lit, disabled = raw_wrap(s["literal"]), s["underscored"]
        dis = ', disabledReason: "underscore attribute"' if disabled else ""
        if "\n" in lit:
            lines += [
                "    SwiftSnippet(",
                f'        label: "{s["label"]}",',
                f"        source: {lit},",
                f'        origin: "{s["origin"]}",',
                f'        syntaxVersion: "{VERSION}"' + ("," if disabled else ""),
            ]
            if disabled:
                lines.append('        disabledReason: "underscore attribute"')
            lines.append("    ),")
        else:
            lines.append(
                f'    SwiftSnippet(label: "{s["label"]}", source: {lit}, '
                f'origin: "{s["origin"]}", syntaxVersion: "{VERSION}"{dis}),'
            )
    lines.append("]")
    return "\n".join(lines)


DOMAINS = [
    ("ExpressionTests.swift",  "expressionRejectSnippets"),
    ("DeclarationTests.swift", "declarationRejectSnippets"),
    ("StatementTests.swift",   "statementRejectSnippets"),
    ("TypeTests.swift",        "typeRejectSnippets"),
    ("PatternTests.swift",     "patternRejectSnippets"),
    ("AttributeTests.swift",   "attributeRejectSnippets"),
]

HEADER = '''//
//  SwiftSyntaxRejects.swift
//  AdventTests
//
//  GENERATED by tools/extract_rejects.py — do not edit by hand; re-run the harvester.
//
//  The NEGATIVE corpus: swift-syntax `assertParse(..., diagnostics:)` cases (invalid /
//  error-recovery inputs) that the accept-extractor skips. Diagnostic markers are
//  stripped, leaving the malformed source.
//
//  Two categories (see TESTING.md):
//    • "SwiftSyntax rejects" — baseline, asserts swift-syntax flags an error. A failure
//      here = a mis-harvested non-error case (warnings-only / valid) → prune candidate.
//    • "Advent rejects"      — asserts Advent produces NO full-span parse. Advent's
//      compiler-faithful grammar correctly rejects most of this negative corpus (GREEN);
//      the remaining RED cases are the reject-parity frontier — inputs Advent still
//      wrongly ACCEPTS (e.g. trailing-closure-in-condition and the other ~32 `.basic`
//      predicates). Track the red count against a baseline, like `treesMatch`.
//

import Testing
import Foundation
import SwiftSyntax
import SwiftParser
'''

SUITE = '''
let allRejectSnippets: [SwiftSnippet] =
    expressionRejectSnippets + declarationRejectSnippets + statementRejectSnippets
    + typeRejectSnippets + patternRejectSnippets + attributeRejectSnippets
    + translatedRejectSnippets

@Suite("SwiftSyntax - Rejects — negative corpus")
struct RejectSyntaxTests {

    // Baseline: these ARE swift-syntax error cases. A failure here means the harvest
    // captured a non-error case (e.g. warnings-only) — a prune candidate, not a bug.
    @Test("SwiftSyntax rejects", .tags(.swiftSyntaxReference), arguments: allRejectSnippets)
    func swiftSyntaxRejects(_ snippet: SwiftSnippet) throws {
        guard snippet.disabledReason == nil else { return }
        let parsed = Parser.parse(source: snippet.source)
        #expect(parsed.hasError, "Expected swift-syntax to flag an error: \\(snippet.source)")
    }

    // Advent SHOULD reject (no full-span parse). GREEN when it does; the RED cases are
    // the reject-parity frontier — invalid inputs Advent still wrongly accepts (the
    // `.basic`/`atValidTrailingClosure` family and other predicate gaps). Track red
    // against a baseline.
    @Test("Advent rejects", arguments: allRejectSnippets)
    func adventRejects(_ snippet: SwiftSnippet) throws {
        guard snippet.disabledReason == nil else { return }
        let result = try adventParse(snippet)
        #expect(result == nil, "Advent wrongly accepted invalid input '\\(snippet.label)': \\(snippet.source)")
    }
}
'''


def main():
    parts = [HEADER]
    total = 0
    for fname, arr in DOMAINS:
        snips = collect_rejects(os.path.join(TESTS_DIR, fname))
        total += len(snips)
        parts.append(f"\n// {fname}: {len(snips)} reject snippets\n" + fmt_array(snips, arr))
        print(f"// {arr}: {len(snips)}", file=sys.stderr)

    # translated: many files, per-func counters namespaced by file to avoid collisions
    tr = []
    for fp in sorted(glob.glob(os.path.join(TESTS_DIR, "translated", "*.swift"))):
        tr += collect_rejects(fp)
    total += len(tr)
    parts.append(f"\n// translated ({total and 'combined'}): {len(tr)} reject snippets\n"
                 + fmt_array(tr, "translatedRejectSnippets"))
    print(f"// translatedRejectSnippets: {len(tr)}", file=sys.stderr)

    parts.append(SUITE)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")
    print(f"// TOTAL reject snippets: {total} -> {os.path.relpath(OUT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
