#!/usr/bin/env python3
"""Cut short top-level declarations out of real Swift files into a fuzzer seed corpus.

A slice starts at a column-0 line that opens a declaration (`func`, `struct`, `extension`, …, with
optional attributes/modifiers) and ends at the next column-0 `}` line. Only slices of at most
--max-lines lines are kept, so each probe stays fast. Output uses the `### label` seed format.

    tools/slice_swift_sources.py --out SwiftSyntaxFuzzer/seeds/real-source.txt DIR [DIR …]
"""
import argparse
import pathlib
import random
import re

START = re.compile(r'^(@\w+(\([^)]*\))?\s+)*((public|internal|private|fileprivate|package|open|final|static|'
                   r'nonisolated|indirect)\s+)*(func|struct|class|enum|extension|protocol|actor|init|var|let)\b')


def slices(path, max_lines):
    lines = path.read_text(errors="ignore").splitlines()
    i = 0
    while i < len(lines):
        if START.match(lines[i]):
            for j in range(i, min(len(lines), i + max_lines)):
                if lines[j] == "}" or (j == i and not lines[i].rstrip().endswith("{")):
                    yield i, "\n".join(lines[i:j + 1])
                    i = j
                    break
        i += 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dirs", nargs="+")
    ap.add_argument("--out", required=True)
    ap.add_argument("--max-lines", type=int, default=30)
    ap.add_argument("--limit", type=int, default=3000)
    ap.add_argument("--seed", type=int, default=2026)
    args = ap.parse_args()

    found = {}
    for d in args.dirs:
        for f in sorted(pathlib.Path(d).rglob("*.swift")):
            for line, text in slices(f, args.max_lines):
                if "\n### " not in text and len(text) > 20:
                    found.setdefault(text, f"real:{f.stem}:{line + 1}")
    items = sorted(found.items(), key=lambda kv: kv[1])
    random.Random(args.seed).shuffle(items)
    items = items[: args.limit]
    with open(args.out, "w") as out:
        out.write("# Generated by tools/slice_swift_sources.py — do not edit; re-run instead.\n\n")
        for text, label in items:
            out.write(f"### {label}\n{text}\n\n")
    print(f"{len(found)} slices found, {len(items)} written to {args.out}")


if __name__ == "__main__":
    main()
